### PR TITLE
add docs section for website integration

### PR DESCRIPTION
**Pull request by Ankurk99**
Ref: #2

### CODE REVIEW

**Review by johnwalicki — APPROVED** [review]
If I understand this, you're moving the README down one level into a docs/ directory
Approved.

**Review by johnwalicki — APPROVED** [review]
Approved

**Comment by Ankurk99** [comment]
> If I understand this, you're moving the README down one level into a docs/ directory

Yes, so as to replicate the GA like this: https://github.com/open-horizon/anax/blob/master/.github/workflows/copydocs.yml

**Review by johnwalicki — APPROVED** [review]
Appoved

**Pull request merged**
