### PR TITLE
fix grammatical errors and also test the Github action

### PR DESCRIPTION
**Pull request by Ankurk99**
Ref: https://github.com/open-horizon/open-horizon.github.io/issues/304

### CODE REVIEW

**Review by johnwalicki — APPROVED** [review]
LGTM - will watch the GHA run.

**Comment by johnwalicki** [comment]
@joewxboy I'm confused. The Copy Docs GHA didn't run.  I inspected the 
https://github.com/open-horizon/kubearmor-integration/blob/main/.github/workflows/copy-docs.yml
and it looks fine.  I don't see why it didn't run - 
https://github.com/open-horizon/kubearmor-integration/actions/workflows/copy-docs.yml

**Comment by Ankurk99** [comment]
Ig the github action didn't run because of the file path, here is the PR which might fix this: https://github.com/open-horizon/kubearmor-integration/pull/8

**Comment by Ankurk99** [comment]
I was able to run the GA on my fork with the following changes: https://github.com/Ankurk99/kubearmor-integration/actions/runs/2980943005

**Pull request merged**
